---                                                                                   
output: github_document        
title: pafr demo
---                                                                                   
                  

# Comparative genomics in fungi


```{r, echo=FALSE}
library(ggplot2)
theme_set(theme_bw(base_size=16))
knitr::opts_chunk$set(fig.width=12, fig.height=8) 
```
```{bash, setup}
bash scripts/download_genomes.sh
echo 'export "MM_CPU=5"' > .shell_vars
```

```{bash}
source .shell_vars
if [ ! -f data/ali/aflav_ali.paf ];
then
    minimap2 -t ${MM_CPU} -cx asm5 data/seqs/A_flav_CA14.fna.gz data/seqs/A_flav_SU-16.fna.gz > data/ali/aflav_ali.paf
fi
```

```{r}
library(pafr)

asper <- read_paf("data/ali/aflav_ali.paf")
asper
```

```{r}
asper_clean <- filter_secondary_alignments(asper)
dotplot(asper_clean, order_by="qstart", label_seqs=TRUE)
```

```{r}
plot_synteny(asper, t_chrom="CP061809.1", q_chrom="CP047251.1", rc=TRUE)
```

```{r}
inv <- subset(asper, tname=="CP061809.1" & qname=="CP047251.1" & strand=="+")
inversion_intervals <-  query_bed(inv)
head(inversion_intervals)
```


```{r}
write_bed(inversion_intervals, "data/results/inversion_query.bed")
```

```{sh}
bedtools merge -d 5000 -i data/results/inversion_query.bed
```

# Comparing draft and finished genome assemblies


```{bash}
source .shell_vars
if [ ! -f data/ali/parrots.paf.gz ]
then
    minimap2 -t ${MM_CPU} -cx asm20 data/seqs/kea.fna.gz data/seqs/kakapo.fna.gz | gzip > data/ali/parrots.paf.gz
fi
```

```{r}
parrots <- read_paf("data/ali/parrots.paf.gz")
hq_parrots <- subset(filter_secondary_alignments(parrots), mapq > 50)
hq_parrots
```


```{r}
dotplot(hq_parrots, order_by="qstart", dashes=FALSE ,label_seqs=TRUE) 
```

```{r}
kea_wing <- "#D73202"
ggplot(hq_parrots, aes(alen/tlen)) + 
    geom_histogram(fill=kea_wing, colour='black', binwidth=0.05) + 
    scale_x_continuous()
```

```{r}
subset(hq_parrots, alen /tlen > 0.99)
```

```{r}
sex_chrom_map <- c("CM013773.2" = "Z", "CM013763.2" = "W")
sex_chrom_ali <- subset(hq_parrots, qname %in% names(sex_chrom_map))
sex_chrom_ali$qname <- sex_chrom_map[sex_chrom_ali$qname]
dotplot(sex_chrom_ali, order_by="qstart" ,label_seqs=TRUE, dashes=FALSE)
```


